sonar.projectKey=achat-frontend-chakrounkamil-4twin9-groupe-6
sonar.projectName=achat-frontend-chakrounkamil-4twin9-groupe-6

sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**

sonar.language=ts
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=squ_fbb8f5ea3a9f7637b4c70ca7e6db7c099245388e
