sonar.projectKey=achat-frontend-abousssaoudnour-4twin9-group-6
sonar.projectName=achat-frontend-abousssaoudnour-4twin9-groupe-6
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/assets/**

sonar.language=ts
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=squ_dbf36e9aee8161d8afe82d973d9a0ae7802c0788

