version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb  # Automatically create 'achatdb' database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - achat_network

  backend:
    image: achat-backend-nouraboussaoud-4twin9
    container_name: backend-app
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/achatdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"
    networks:
      - achat_network
    restart: on-failure

networks:
  achat_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local  # Ensures data is stored persistently in the volume

