# SonarQube project configuration
sonar.projectKey=achat-backend-abousssaoudnour-4twin9-groupe-6
sonar.projectName=achat-backend-nomprenom-classe-groupe-n
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=src

# Language of the project
sonar.language=java

# Encoding used in the project files
sonar.sourceEncoding=UTF-8

# Path to the compiled classes (adjust if necessary)
sonar.java.binaries=target/classes

# SonarQube server URL and login credentials (replace with your actual token)
sonar.host.url=http://localhost:9000
sonar.login=squ_dbf36e9aee8161d8afe82d973d9a0ae7802c0788
