sonar.projectKey=achat-backend-chakrounkamil-4twin9-groupe-6
sonar.projectName=achat-backend-chakrounkamil-4twin9-groupe-6
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target
sonar.sourceEncoding=UTF-8
